server:
  port: 5000

database:
  psql:
    host: localhost
    port: 5434
    username: postgres
    password: postgres
    database: quiz
    debug: true


auth0:
  issuer: https://dev-cmegn43bvk67a63b.eu.auth0.com
  audience: http://quizz.ndl.thomasgouveia.fr
